export const SIGNIN_ROUTE = '/signin'
export const REG_ROUTE = '/registration'
export const HOME_ROUTE = '/'
export const TASK_ROUTE = '/task'
export const ADD_TASK = 'ADD_TASK'
export const FETCH_TASKS = 'FETCH_TASKS'
export const REMOVE_TASK = 'REMOVE_TASK'
export const SHOW_LOADING = 'SHOW_LOADING'